//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryMgmtSys.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ashwani_Order
    {
        public int Id { get; set; }
        public string ord_id { get; set; }
        public string ordname { get; set; }
        public Nullable<int> qty { get; set; }
        public Nullable<System.DateTime> orddate { get; set; }
        public Nullable<System.DateTime> duedate { get; set; }
        public string manufacturer { get; set; }
        public Nullable<int> sales_per { get; set; }
        public Nullable<int> customer { get; set; }
        public string status { get; set; }
        public Nullable<int> itemid { get; set; }
    
        public virtual Ashwani Ashwani { get; set; }
        public virtual Ashwani_Customer Ashwani_Customer { get; set; }
        public virtual Ashwani_Items Ashwani_Items { get; set; }
    }
}
