//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryMgmtSys.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ashwani_Items
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ashwani_Items()
        {
            this.Ashwani_Order = new HashSet<Ashwani_Order>();
        }
    
        public int Id { get; set; }
        public string id_item { get; set; }
        public string itname { get; set; }
        public Nullable<int> qty { get; set; }
        public Nullable<double> sold_qty { get; set; }
        public Nullable<double> cost { get; set; }
        public Nullable<System.DateTime> itdate { get; set; }
        public string manufacturer { get; set; }
        public string sales_per { get; set; }
        public string address { get; set; }
        public string telephone { get; set; }
        public Nullable<double> itsale { get; set; }
        public Nullable<int> cat_id { get; set; }
    
        public virtual Ashwani_Category Ashwani_Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ashwani_Order> Ashwani_Order { get; set; }
    }
}
