//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryMgmtSys.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Ashwani_EMployee
    {
        [Required(ErrorMessage = "please provide id")]
        [RegularExpression("^[0-9]+$", ErrorMessage = "Id should be numeric")]

        public int Id { get; set; }
        [Required(ErrorMessage = "please provide employee name")]
        public string EmpName { get; set; }
        [Required(ErrorMessage = "please provide employee address")]
        public string EmpAddress { get; set; }
        [Range(25, 58, ErrorMessage = "Employee Age should be between 25 and 58")]
        public Nullable<int> EmpAge { get; set; }
        [RegularExpression("^[0-9]+$", ErrorMessage = "salary should be numeric")]
        [Required]
        public Nullable<double> EmpSalary { get; set; }
        [Required(ErrorMessage ="Please enter Date of Birth")]
        public Nullable<System.DateTime> DateOfBirth { get; set; }
    }
}
