//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryMgmtSys.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class C3IT_DOTNET_TESTEntities13 : DbContext
    {
        public C3IT_DOTNET_TESTEntities13()
            : base("name=C3IT_DOTNET_TESTEntities13")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Ashwani> Ashwanis { get; set; }
        public virtual DbSet<Ashwani_Category> Ashwani_Category { get; set; }
        public virtual DbSet<Ashwani_Customer> Ashwani_Customer { get; set; }
        public virtual DbSet<Ashwani_Items> Ashwani_Items { get; set; }
        public virtual DbSet<Ashwani_Order> Ashwani_Order { get; set; }
        public virtual DbSet<Ashwani_EMployee> Ashwani_EMployee { get; set; }
    }
}
